# Generated by Django 4.2.4 on 2023-10-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dishes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="stripe_product_price_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
