# Generated by Django 4.2.4 on 2023-09-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commentary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(verbose_name="comment on post")),
            ],
            options={
                "verbose_name_plural": "commentaries",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "very bad"),
                            (2, "bad"),
                            (3, "maybe"),
                            (4, "good"),
                            (5, "excellent"),
                        ]
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["dish__name"],
            },
        ),
    ]
