# Generated by Django 4.2.4 on 2023-10-04 18:56

import phonenumber_field.modelfields
from django.db import migrations

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128,
                region="UA",
                validators=[users.models.validate_ukrainian_phone_number],
            ),
        ),
    ]
